// STAGE II · 主题词 (Society/Work/Culture/City/Travel)
window.VOCAB = (window.VOCAB || []).concat([

// ============== 社会 SOCIETY (~180) ==============
["s2","society","abolish","əˈbɒlɪʃ","v.","废除"],
["s2","society","abuse","əˈbjuːz","n./v.","虐待"],
["s2","society","activist","ˈæktɪvɪst","n.","活动家"],
["s2","society","adolescent","ˌædəˈlesnt","n./adj.","青少年"],
["s2","society","ageing","ˈeɪdʒɪŋ","adj.","老龄化的"],
["s2","society","aid","eɪd","n./v.","援助"],
["s2","society","alienate","ˈeɪliəneɪt","v.","疏远"],
["s2","society","ally","ˈælaɪ","n./v.","盟友"],
["s2","society","ancestor","ˈænsestə(r)","n.","祖先"],
["s2","society","attitude","ˈætɪtjuːd","n.","态度"],
["s2","society","awareness","əˈweənəs","n.","意识"],
["s2","society","background","ˈbækɡraʊnd","n.","背景"],
["s2","society","beggar","ˈbeɡə(r)","n.","乞丐"],
["s2","society","belief","bɪˈliːf","n.","信仰"],
["s2","society","bias","ˈbaɪəs","n.","偏见"],
["s2","society","birth rate","bɜːθ reɪt","n.","出生率"],
["s2","society","budget","ˈbʌdʒɪt","n.","预算"],
["s2","society","bully","ˈbʊli","n./v.","欺凌"],
["s2","society","campaign","kæmˈpeɪn","n.","运动"],
["s2","society","capitalism","ˈkæpɪtəlɪzəm","n.","资本主义"],
["s2","society","cause","kɔːz","n.","事业"],
["s2","society","census","ˈsensəs","n.","人口普查"],
["s2","society","ceremony","ˈserəməni","n.","典礼"],
["s2","society","charity","ˈtʃærəti","n.","慈善"],
["s2","society","child labour","tʃaɪld ˈleɪbə(r)","n.","童工"],
["s2","society","citizenship","ˈsɪtɪzənʃɪp","n.","公民身份"],
["s2","society","civil rights","ˈsɪvl raɪts","n.","公民权利"],
["s2","society","civilisation","ˌsɪvəlaɪˈzeɪʃn","n.","文明"],
["s2","society","class","klɑːs","n.","阶级"],
["s2","society","cohesion","kəʊˈhiːʒn","n.","凝聚力"],
["s2","society","colony","ˈkɒləni","n.","殖民地"],
["s2","society","commitment","kəˈmɪtmənt","n.","承诺"],
["s2","society","community","kəˈmjuːnəti","n.","社区","Strong local <b>communities</b> are key to mental wellbeing.","C9 R"],
["s2","society","conflict","ˈkɒnflɪkt","n.","冲突"],
["s2","society","conform","kənˈfɔːm","v.","遵从"],
["s2","society","conservative","kənˈsɜːvətɪv","adj.","保守的"],
["s2","society","constitution","ˌkɒnstɪˈtjuːʃn","n.","宪法"],
["s2","society","controversy","ˈkɒntrəvɜːsi","n.","争议"],
["s2","society","convention","kənˈvenʃn","n.","习俗；公约"],
["s2","society","corruption","kəˈrʌpʃn","n.","腐败"],
["s2","society","crime","kraɪm","n.","犯罪"],
["s2","society","criminal","ˈkrɪmɪnl","n./adj.","罪犯"],
["s2","society","crisis","ˈkraɪsɪs","n.","危机"],
["s2","society","cultural","ˈkʌltʃərəl","adj.","文化的"],
["s2","society","custom","ˈkʌstəm","n.","习俗"],
["s2","society","democracy","dɪˈmɒkrəsi","n.","民主"],
["s2","society","demographic","ˌdeməˈɡræfɪk","adj.","人口的","Japan faces severe <b>demographic</b> challenges due to its ageing population.","C12 R"],
["s2","society","deprivation","ˌdeprɪˈveɪʃn","n.","贫困"],
["s2","society","developing country","dɪˈveləpɪŋ ˈkʌntri","n.","发展中国家"],
["s2","society","disabled","dɪsˈeɪbld","adj.","残疾的"],
["s2","society","discrimination","dɪˌskrɪmɪˈneɪʃn","n.","歧视"],
["s2","society","disparity","dɪˈspærəti","n.","差异"],
["s2","society","diverse","daɪˈvɜːs","adj.","多样的"],
["s2","society","diversity","daɪˈvɜːsəti","n.","多样性"],
["s2","society","division","dɪˈvɪʒn","n.","分裂"],
["s2","society","domestic","dəˈmestɪk","adj.","国内的；家庭的"],
["s2","society","economy","ɪˈkɒnəmi","n.","经济"],
["s2","society","elderly","ˈeldəli","adj.","老年的"],
["s2","society","election","ɪˈlekʃn","n.","选举"],
["s2","society","elite","eɪˈliːt","n./adj.","精英"],
["s2","society","emigrate","ˈemɪɡreɪt","v.","移居海外"],
["s2","society","employment","ɪmˈplɔɪmənt","n.","就业"],
["s2","society","equality","iˈkwɒləti","n.","平等"],
["s2","society","ethnic","ˈeθnɪk","adj.","民族的"],
["s2","society","ethics","ˈeθɪks","n.","伦理"],
["s2","society","extended family","ɪkˈstendɪd ˈfæməli","n.","大家庭"],
["s2","society","famine","ˈfæmɪn","n.","饥荒"],
["s2","society","feminism","ˈfemɪnɪzəm","n.","女权主义"],
["s2","society","feudal","ˈfjuːdl","adj.","封建的"],
["s2","society","funding","ˈfʌndɪŋ","n.","资金"],
["s2","society","gender","ˈdʒendə(r)","n.","性别"],
["s2","society","generation","ˌdʒenəˈreɪʃn","n.","代"],
["s2","society","globalisation","ˌɡləʊbəlaɪˈzeɪʃn","n.","全球化"],
["s2","society","government","ˈɡʌvənmənt","n.","政府"],
["s2","society","heritage","ˈherɪtɪdʒ","n.","遗产"],
["s2","society","hierarchy","ˈhaɪərɑːki","n.","等级制度"],
["s2","society","homeless","ˈhəʊmləs","adj.","无家可归的"],
["s2","society","human rights","ˈhjuːmən raɪts","n.","人权"],
["s2","society","ideology","ˌaɪdiˈɒlədʒi","n.","意识形态"],
["s2","society","immigrant","ˈɪmɪɡrənt","n.","移民"],
["s2","society","immigrate","ˈɪmɪɡreɪt","v.","移入"],
["s2","society","income inequality","ˈɪnkʌm ˌɪnɪˈkwɒləti","n.","收入不平等"],
["s2","society","individualism","ˌɪndɪˈvɪdʒuəlɪzəm","n.","个人主义"],
["s2","society","inequality","ˌɪnɪˈkwɒləti","n.","不平等","Income <b>inequality</b> has widened in most developed economies.","BC W2"],
["s2","society","infrastructure","ˈɪnfrəstrʌktʃə(r)","n.","基础设施"],
["s2","society","integration","ˌɪntɪˈɡreɪʃn","n.","融合","Language classes accelerate the <b>integration</b> of newly arrived migrants.","C14 W2"],
["s2","society","interact","ˌɪntərˈækt","v.","互动"],
["s2","society","justice","ˈdʒʌstɪs","n.","正义"],
["s2","society","juvenile","ˈdʒuːvənaɪl","adj.","青少年的"],
["s2","society","law","lɔː","n.","法律"],
["s2","society","liberal","ˈlɪbərəl","adj.","自由的"],
["s2","society","living standard","ˈlɪvɪŋ ˈstændəd","n.","生活水平"],
["s2","society","loyalty","ˈlɔɪəlti","n.","忠诚"],
["s2","society","majority","məˈdʒɒrəti","n.","多数"],
["s2","society","marriage","ˈmærɪdʒ","n.","婚姻"],
["s2","society","media","ˈmiːdiə","n.","媒体"],
["s2","society","middle class","ˈmɪdl klɑːs","n.","中产阶级"],
["s2","society","migration","maɪˈɡreɪʃn","n.","迁徙"],
["s2","society","minority","maɪˈnɒrəti","n.","少数群体"],
["s2","society","misconception","ˌmɪskənˈsepʃn","n.","误解"],
["s2","society","modernise","ˈmɒdənaɪz","v.","现代化"],
["s2","society","monarchy","ˈmɒnəki","n.","君主制"],
["s2","society","moral","ˈmɒrəl","adj.","道德的"],
["s2","society","movement","ˈmuːvmənt","n.","运动"],
["s2","society","multiculturalism","ˌmʌltiˈkʌltʃərəlɪzəm","n.","多元文化"],
["s2","society","negotiate","nɪˈɡəʊʃieɪt","v.","谈判"],
["s2","society","norm","nɔːm","n.","规范"],
["s2","society","oppression","əˈpreʃn","n.","压迫"],
["s2","society","parliament","ˈpɑːləmənt","n.","议会"],
["s2","society","patriarchy","ˈpeɪtriɑːki","n.","父权制"],
["s2","society","penalty","ˈpenəlti","n.","处罚"],
["s2","society","pension","ˈpenʃn","n.","养老金"],
["s2","society","persecution","ˌpɜːsɪˈkjuːʃn","n.","迫害"],
["s2","society","policy","ˈpɒləsi","n.","政策"],
["s2","society","politics","ˈpɒlətɪks","n.","政治"],
["s2","society","poverty","ˈpɒvəti","n.","贫困"],
["s2","society","prejudice","ˈpredʒudɪs","n.","偏见"],
["s2","society","privilege","ˈprɪvəlɪdʒ","n.","特权"],
["s2","society","prohibit","prəˈhɪbɪt","v.","禁止"],
["s2","society","protest","ˈprəʊtest","n./v.","抗议"],
["s2","society","public","ˈpʌblɪk","adj.","公共的"],
["s2","society","race","reɪs","n.","种族"],
["s2","society","racism","ˈreɪsɪzəm","n.","种族主义"],
["s2","society","reform","rɪˈfɔːm","n./v.","改革"],
["s2","society","refugee","ˌrefjuˈdʒiː","n.","难民"],
["s2","society","regulate","ˈreɡjuleɪt","v.","管制"],
["s2","society","religion","rɪˈlɪdʒən","n.","宗教"],
["s2","society","retire","rɪˈtaɪə(r)","v.","退休"],
["s2","society","ritual","ˈrɪtʃuəl","n.","仪式"],
["s2","society","rural","ˈrʊərəl","adj.","农村的"],
["s2","society","secular","ˈsekjələ(r)","adj.","世俗的"],
["s2","society","segregation","ˌseɡrɪˈɡeɪʃn","n.","种族隔离"],
["s2","society","sexism","ˈseksɪzəm","n.","性别歧视"],
["s2","society","single parent","ˈsɪŋɡl ˈpeərənt","n.","单亲"],
["s2","society","slum","slʌm","n.","贫民窟"],
["s2","society","social","ˈsəʊʃl","adj.","社会的"],
["s2","society","social security","ˈsəʊʃl sɪˈkjʊərəti","n.","社会保障"],
["s2","society","society","səˈsaɪəti","n.","社会"],
["s2","society","solidarity","ˌsɒlɪˈdærəti","n.","团结"],
["s2","society","standard of living","ˈstændəd əv ˈlɪvɪŋ","n.","生活水平"],
["s2","society","status","ˈsteɪtəs","n.","地位"],
["s2","society","stereotype","ˈsteriətaɪp","n.","刻板印象"],
["s2","society","subsidy","ˈsʌbsədi","n.","补贴"],
["s2","society","subsidise","ˈsʌbsɪdaɪz","v.","补贴"],
["s2","society","suburb","ˈsʌbɜːb","n.","郊区"],
["s2","society","suffrage","ˈsʌfrɪdʒ","n.","选举权"],
["s2","society","tax","tæks","n./v.","税"],
["s2","society","taxation","tækˈseɪʃn","n.","税收"],
["s2","society","tradition","trəˈdɪʃn","n.","传统"],
["s2","society","tribe","traɪb","n.","部落"],
["s2","society","unemployment","ˌʌnɪmˈplɔɪmənt","n.","失业"],
["s2","society","union","ˈjuːniən","n.","工会"],
["s2","society","upper class","ˈʌpə(r) klɑːs","n.","上层阶级"],
["s2","society","urban","ˈɜːbən","adj.","城市的"],
["s2","society","urbanisation","ˌɜːbənaɪˈzeɪʃn","n.","城市化","Rapid <b>urbanisation</b> has put huge pressure on local infrastructure.","C13 W1"],
["s2","society","values","ˈvæljuːz","n.","价值观"],
["s2","society","violence","ˈvaɪələns","n.","暴力"],
["s2","society","vulnerable","ˈvʌlnərəbl","adj.","脆弱的"],
["s2","society","welfare","ˈwelfeə(r)","n.","福利","The state provides comprehensive <b>welfare</b> support for the elderly.","C11 L S3"],
["s2","society","working class","ˈwɜːkɪŋ klɑːs","n.","工人阶级"],
["s2","society","youth","juːθ","n.","青年"],

// ============== 工作 / 经济 WORK & ECONOMY (~200) ==============
["s2","work","accounting","əˈkaʊntɪŋ","n.","会计"],
["s2","work","achievement","əˈtʃiːvmənt","n.","成就"],
["s2","work","administration","ədˌmɪnɪˈstreɪʃn","n.","行政管理"],
["s2","work","advertisement","ədˈvɜːtɪsmənt","n.","广告"],
["s2","work","agency","ˈeɪdʒənsi","n.","机构"],
["s2","work","agreement","əˈɡriːmənt","n.","协议"],
["s2","work","ambition","æmˈbɪʃn","n.","抱负"],
["s2","work","appointment","əˈpɔɪntmənt","n.","约会；任命"],
["s2","work","apprentice","əˈprentɪs","n.","学徒"],
["s2","work","aspire","əˈspaɪə(r)","v.","渴望"],
["s2","work","balance","ˈbæləns","n./v.","平衡"],
["s2","work","bankruptcy","ˈbæŋkrʌptsi","n.","破产"],
["s2","work","bargain","ˈbɑːɡən","n./v.","便宜货；讨价还价"],
["s2","work","benefit","ˈbenɪfɪt","n.","福利"],
["s2","work","bonus","ˈbəʊnəs","n.","奖金"],
["s2","work","brand","brænd","n.","品牌"],
["s2","work","budget","ˈbʌdʒɪt","n.","预算"],
["s2","work","bureaucracy","bjʊəˈrɒkrəsi","n.","官僚"],
["s2","work","business","ˈbɪznəs","n.","生意"],
["s2","work","candidate","ˈkændɪdət","n.","候选人"],
["s2","work","career","kəˈrɪə(r)","n.","职业"],
["s2","work","capital","ˈkæpɪtl","n./adj.","资本；首都"],
["s2","work","client","ˈklaɪənt","n.","客户"],
["s2","work","colleague","ˈkɒliːɡ","n.","同事","Supportive <b>colleagues</b> can make a stressful job bearable.","C10 S1"],
["s2","work","commerce","ˈkɒmɜːs","n.","商业"],
["s2","work","commodity","kəˈmɒdəti","n.","商品"],
["s2","work","commission","kəˈmɪʃn","n.","佣金；委员会"],
["s2","work","commute","kəˈmjuːt","v./n.","通勤","A long daily <b>commute</b> can negatively affect both health and family life.","C13 S3"],
["s2","work","company","ˈkʌmpəni","n.","公司"],
["s2","work","compensation","ˌkɒmpenˈseɪʃn","n.","补偿"],
["s2","work","competition","ˌkɒmpəˈtɪʃn","n.","竞争"],
["s2","work","conference","ˈkɒnfərəns","n.","会议"],
["s2","work","consumer","kənˈsjuːmə(r)","n.","消费者"],
["s2","work","contract","ˈkɒntrækt","n.","合同"],
["s2","work","corporate","ˈkɔːpərət","adj.","公司的"],
["s2","work","corporation","ˌkɔːpəˈreɪʃn","n.","公司"],
["s2","work","cost-effective","kɒst ɪˈfektɪv","adj.","划算的"],
["s2","work","CV","ˌsiː ˈviː","n.","简历"],
["s2","work","deadline","ˈdedlaɪn","n.","截止日期"],
["s2","work","deal","diːl","n.","交易"],
["s2","work","deficit","ˈdefɪsɪt","n.","赤字"],
["s2","work","delegate","ˈdelɪɡət","v./n.","委派"],
["s2","work","demand","dɪˈmɑːnd","n.","需求"],
["s2","work","depreciate","dɪˈpriːʃieɪt","v.","贬值"],
["s2","work","developer","dɪˈveləpə(r)","n.","开发者"],
["s2","work","dismiss","dɪsˈmɪs","v.","解雇"],
["s2","work","distribution","ˌdɪstrɪˈbjuːʃn","n.","分配；分布"],
["s2","work","economic","ˌiːkəˈnɒmɪk","adj.","经济的"],
["s2","work","economist","ɪˈkɒnəmɪst","n.","经济学家"],
["s2","work","employee","ɪmˈplɔɪiː","n.","员工"],
["s2","work","employer","ɪmˈplɔɪə(r)","n.","雇主"],
["s2","work","enterprise","ˈentəpraɪz","n.","企业"],
["s2","work","entrepreneur","ˌɒntrəprəˈnɜː(r)","n.","企业家"],
["s2","work","equity","ˈekwəti","n.","股权"],
["s2","work","executive","ɪɡˈzekjətɪv","n./adj.","执行者；行政的"],
["s2","work","experience","ɪkˈspɪəriəns","n.","经验"],
["s2","work","expertise","ˌekspɜːˈtiːz","n.","专长"],
["s2","work","factory","ˈfæktri","n.","工厂"],
["s2","work","feedback","ˈfiːdbæk","n.","反馈"],
["s2","work","finance","ˈfaɪnæns","n.","金融"],
["s2","work","financial","faɪˈnænʃl","adj.","金融的"],
["s2","work","fired","ˈfaɪəd","adj.","被解雇的"],
["s2","work","firm","fɜːm","n.","公司"],
["s2","work","flexible","ˈfleksəbl","adj.","灵活的"],
["s2","work","freelance","ˈfriːlɑːns","adj./n.","自由职业的"],
["s2","work","goods","ɡʊdz","n.","商品"],
["s2","work","gross","ɡrəʊs","adj.","总的"],
["s2","work","headhunter","ˈhedhʌntə(r)","n.","猎头"],
["s2","work","hire","ˈhaɪə(r)","v.","雇佣"],
["s2","work","HR","ˌeɪtʃ ˈɑː(r)","n.","人力资源"],
["s2","work","income","ˈɪnkʌm","n.","收入"],
["s2","work","industrialise","ɪnˈdʌstriəlaɪz","v.","工业化"],
["s2","work","industry","ˈɪndəstri","n.","行业"],
["s2","work","inflation","ɪnˈfleɪʃn","n.","通货膨胀"],
["s2","work","insurance","ɪnˈʃʊərəns","n.","保险"],
["s2","work","intern","ɪnˈtɜːn","n.","实习生"],
["s2","work","internship","ˈɪntɜːnʃɪp","n.","实习"],
["s2","work","interview","ˈɪntəvjuː","n.","面试"],
["s2","work","invoice","ˈɪnvɔɪs","n.","发票"],
["s2","work","job","dʒɒb","n.","工作"],
["s2","work","labour","ˈleɪbə(r)","n.","劳动力"],
["s2","work","labour force","ˈleɪbə(r) fɔːs","n.","劳动力"],
["s2","work","layoff","ˈleɪɒf","n.","裁员"],
["s2","work","leadership","ˈliːdəʃɪp","n.","领导力"],
["s2","work","leave","liːv","n.","休假"],
["s2","work","loan","ləʊn","n.","贷款"],
["s2","work","logo","ˈləʊɡəʊ","n.","标志"],
["s2","work","management","ˈmænɪdʒmənt","n.","管理"],
["s2","work","manager","ˈmænɪdʒə(r)","n.","经理"],
["s2","work","manpower","ˈmænpaʊə(r)","n.","人力"],
["s2","work","manufacture","ˌmænjuˈfæktʃə(r)","v./n.","制造"],
["s2","work","market","ˈmɑːkɪt","n.","市场"],
["s2","work","marketing","ˈmɑːkɪtɪŋ","n.","营销"],
["s2","work","maternity leave","məˈtɜːnəti liːv","n.","产假"],
["s2","work","merchandise","ˈmɜːtʃəndaɪz","n.","商品"],
["s2","work","merger","ˈmɜːdʒə(r)","n.","合并"],
["s2","work","monopoly","məˈnɒpəli","n.","垄断"],
["s2","work","mortgage","ˈmɔːɡɪdʒ","n.","抵押贷款"],
["s2","work","negotiate","nɪˈɡəʊʃieɪt","v.","谈判"],
["s2","work","occupation","ˌɒkjuˈpeɪʃn","n.","职业"],
["s2","work","office","ˈɒfɪs","n.","办公室"],
["s2","work","outsource","ˈaʊtsɔːs","v.","外包"],
["s2","work","overtime","ˈəʊvətaɪm","n.","加班"],
["s2","work","payroll","ˈpeɪrəʊl","n.","工资单"],
["s2","work","pension","ˈpenʃn","n.","养老金"],
["s2","work","performance","pəˈfɔːməns","n.","绩效"],
["s2","work","permanent","ˈpɜːmənənt","adj.","永久的"],
["s2","work","personnel","ˌpɜːsəˈnel","n.","人员"],
["s2","work","portfolio","pɔːtˈfəʊliəʊ","n.","组合"],
["s2","work","poverty","ˈpɒvəti","n.","贫困"],
["s2","work","productivity","ˌprɒdʌkˈtɪvəti","n.","生产率","Studies show that flexible hours can boost <b>productivity</b> by up to 15%.","C14 R"],
["s2","work","profession","prəˈfeʃn","n.","职业"],
["s2","work","profit","ˈprɒfɪt","n.","利润"],
["s2","work","promotion","prəˈməʊʃn","n.","晋升；促销"],
["s2","work","prospect","ˈprɒspekt","n.","前景"],
["s2","work","qualification","ˌkwɒlɪfɪˈkeɪʃn","n.","资格"],
["s2","work","recession","rɪˈseʃn","n.","衰退"],
["s2","work","recruit","rɪˈkruːt","v.","招募","The firm <b>recruited</b> over 200 graduates last year.","C12 L"],
["s2","work","recruitment","rɪˈkruːtmənt","n.","招聘"],
["s2","work","redundancy","rɪˈdʌndənsi","n.","裁员"],
["s2","work","reference","ˈrefrəns","n.","推荐人"],
["s2","work","remote","rɪˈməʊt","adj.","远程的","More companies now allow employees to work <b>remotely</b>.","C16 S3"],
["s2","work","resign","rɪˈzaɪn","v.","辞职"],
["s2","work","resignation","ˌrezɪɡˈneɪʃn","n.","辞职"],
["s2","work","resume","ˈrezjumeɪ","n.","简历"],
["s2","work","retail","ˈriːteɪl","n.","零售"],
["s2","work","retire","rɪˈtaɪə(r)","v.","退休"],
["s2","work","revenue","ˈrevənjuː","n.","收入"],
["s2","work","reward","rɪˈwɔːd","n./v.","奖励"],
["s2","work","salary","ˈsæləri","n.","薪水"],
["s2","work","sales","seɪlz","n.","销售"],
["s2","work","schedule","ˈʃedjuːl","n.","日程"],
["s2","work","sector","ˈsektə(r)","n.","行业"],
["s2","work","service","ˈsɜːvɪs","n.","服务"],
["s2","work","share","ʃeə(r)","n.","股份"],
["s2","work","shift","ʃɪft","n.","班次"],
["s2","work","shortage","ˈʃɔːtɪdʒ","n.","短缺"],
["s2","work","skilled","skɪld","adj.","熟练的"],
["s2","work","staff","stɑːf","n.","员工"],
["s2","work","stakeholder","ˈsteɪkhəʊldə(r)","n.","利益相关者"],
["s2","work","start-up","ˈstɑːt ʌp","n.","初创公司"],
["s2","work","strike","straɪk","n./v.","罢工"],
["s2","work","subsidy","ˈsʌbsədi","n.","补贴"],
["s2","work","supply","səˈplaɪ","n.","供应"],
["s2","work","target","ˈtɑːɡɪt","n.","目标"],
["s2","work","tariff","ˈtærɪf","n.","关税"],
["s2","work","tax","tæks","n.","税"],
["s2","work","trade","treɪd","n.","贸易"],
["s2","work","training","ˈtreɪnɪŋ","n.","培训"],
["s2","work","turnover","ˈtɜːnəʊvə(r)","n.","营业额"],
["s2","work","unemployed","ˌʌnɪmˈplɔɪd","adj.","失业的"],
["s2","work","vacancy","ˈveɪkənsi","n.","空缺"],
["s2","work","vacation","vəˈkeɪʃn","n.","假期"],
["s2","work","wage","weɪdʒ","n.","工资"],
["s2","work","workforce","ˈwɜːkfɔːs","n.","劳动力","Women now make up 47% of the UK <b>workforce</b>.","C11 W1"],
["s2","work","workplace","ˈwɜːkpleɪs","n.","工作场所"],

// ============== 文化 / 媒体 CULTURE & MEDIA (~150) ==============
["s2","culture","abstract","ˈæbstrækt","adj.","抽象的"],
["s2","culture","actor","ˈæktə(r)","n.","演员"],
["s2","culture","aesthetics","esˈθetɪks","n.","美学"],
["s2","culture","album","ˈælbəm","n.","专辑"],
["s2","culture","amateur","ˈæmətə(r)","adj./n.","业余的"],
["s2","culture","ancestral","ænˈsestrəl","adj.","祖先的"],
["s2","culture","anthropology","ˌænθrəˈpɒlədʒi","n.","人类学"],
["s2","culture","appreciate","əˈpriːʃieɪt","v.","欣赏"],
["s2","culture","archaeology","ˌɑːkiˈɒlədʒi","n.","考古学"],
["s2","culture","architecture","ˈɑːkɪtektʃə(r)","n.","建筑"],
["s2","culture","art","ɑːt","n.","艺术"],
["s2","culture","artefact","ˈɑːtɪfækt","n.","手工艺品"],
["s2","culture","artist","ˈɑːtɪst","n.","艺术家"],
["s2","culture","audience","ˈɔːdiəns","n.","观众"],
["s2","culture","author","ˈɔːθə(r)","n.","作者"],
["s2","culture","autobiography","ˌɔːtəbaɪˈɒɡrəfi","n.","自传"],
["s2","culture","awards","əˈwɔːdz","n.","奖项"],
["s2","culture","ballad","ˈbæləd","n.","民谣"],
["s2","culture","band","bænd","n.","乐队"],
["s2","culture","biography","baɪˈɒɡrəfi","n.","传记"],
["s2","culture","blockbuster","ˈblɒkbʌstə(r)","n.","大片"],
["s2","culture","blog","blɒɡ","n.","博客"],
["s2","culture","book","bʊk","n.","书"],
["s2","culture","broadcast","ˈbrɔːdkɑːst","n./v.","广播"],
["s2","culture","canvas","ˈkænvəs","n.","画布"],
["s2","culture","caption","ˈkæpʃn","n.","标题；字幕"],
["s2","culture","cathedral","kəˈθiːdrəl","n.","大教堂"],
["s2","culture","celebrity","səˈlebrəti","n.","名人"],
["s2","culture","censor","ˈsensə(r)","v.","审查"],
["s2","culture","ceremony","ˈserəməni","n.","典礼"],
["s2","culture","cinema","ˈsɪnəmə","n.","电影院"],
["s2","culture","classical","ˈklæsɪkl","adj.","古典的"],
["s2","culture","collection","kəˈlekʃn","n.","收藏"],
["s2","culture","comedy","ˈkɒmədi","n.","喜剧"],
["s2","culture","comic","ˈkɒmɪk","n./adj.","漫画"],
["s2","culture","compose","kəmˈpəʊz","v.","创作"],
["s2","culture","concert","ˈkɒnsət","n.","音乐会"],
["s2","culture","contemporary","kənˈtempərəri","adj.","当代的"],
["s2","culture","convention","kənˈvenʃn","n.","传统；惯例"],
["s2","culture","craft","krɑːft","n.","工艺"],
["s2","culture","creative","kriˈeɪtɪv","adj.","创造性的"],
["s2","culture","critic","ˈkrɪtɪk","n.","批评家"],
["s2","culture","cultural","ˈkʌltʃərəl","adj.","文化的"],
["s2","culture","culture","ˈkʌltʃə(r)","n.","文化"],
["s2","culture","dance","dɑːns","n./v.","舞蹈"],
["s2","culture","debut","ˈdeɪbjuː","n.","首次亮相"],
["s2","culture","director","dəˈrektə(r)","n.","导演"],
["s2","culture","documentary","ˌdɒkjuˈmentri","n.","纪录片"],
["s2","culture","drama","ˈdrɑːmə","n.","戏剧"],
["s2","culture","editor","ˈedɪtə(r)","n.","编辑"],
["s2","culture","entertainment","ˌentəˈteɪnmənt","n.","娱乐"],
["s2","culture","ethnic","ˈeθnɪk","adj.","民族的"],
["s2","culture","exhibition","ˌeksɪˈbɪʃn","n.","展览"],
["s2","culture","exhibit","ɪɡˈzɪbɪt","v./n.","展出；展品"],
["s2","culture","fame","feɪm","n.","名声"],
["s2","culture","fashion","ˈfæʃn","n.","时尚"],
["s2","culture","feature film","ˈfiːtʃə(r) fɪlm","n.","故事片"],
["s2","culture","festival","ˈfestɪvl","n.","节日"],
["s2","culture","fiction","ˈfɪkʃn","n.","小说；虚构"],
["s2","culture","film","fɪlm","n.","电影"],
["s2","culture","folk","fəʊk","adj./n.","民间的"],
["s2","culture","gallery","ˈɡæləri","n.","画廊"],
["s2","culture","genre","ˈʒɒnrə","n.","流派"],
["s2","culture","heritage","ˈherɪtɪdʒ","n.","遗产"],
["s2","culture","historic","hɪˈstɒrɪk","adj.","具有历史意义的"],
["s2","culture","horror","ˈhɒrə(r)","n.","恐怖"],
["s2","culture","imagination","ɪˌmædʒɪˈneɪʃn","n.","想象力"],
["s2","culture","influence","ˈɪnfluəns","n.","影响"],
["s2","culture","interview","ˈɪntəvjuː","n.","采访"],
["s2","culture","journalist","ˈdʒɜːnəlɪst","n.","记者"],
["s2","culture","landmark","ˈlændmɑːk","n.","地标"],
["s2","culture","language","ˈlæŋɡwɪdʒ","n.","语言"],
["s2","culture","legacy","ˈleɡəsi","n.","遗产"],
["s2","culture","legend","ˈledʒənd","n.","传说"],
["s2","culture","literature","ˈlɪtrətʃə(r)","n.","文学"],
["s2","culture","magazine","ˌmæɡəˈziːn","n.","杂志"],
["s2","culture","masterpiece","ˈmɑːstəpiːs","n.","杰作"],
["s2","culture","media","ˈmiːdiə","n.","媒体"],
["s2","culture","melody","ˈmelədi","n.","旋律"],
["s2","culture","movie","ˈmuːvi","n.","电影"],
["s2","culture","museum","mjuˈziːəm","n.","博物馆"],
["s2","culture","music","ˈmjuːzɪk","n.","音乐"],
["s2","culture","musical","ˈmjuːzɪkl","adj./n.","音乐的；音乐剧"],
["s2","culture","musician","mjuˈzɪʃn","n.","音乐家"],
["s2","culture","mythology","mɪˈθɒlədʒi","n.","神话"],
["s2","culture","narrative","ˈnærətɪv","n./adj.","叙述"],
["s2","culture","newspaper","ˈnjuːzpeɪpə(r)","n.","报纸"],
["s2","culture","novel","ˈnɒvl","n.","小说"],
["s2","culture","novelist","ˈnɒvəlɪst","n.","小说家"],
["s2","culture","opera","ˈɒprə","n.","歌剧"],
["s2","culture","orchestra","ˈɔːkɪstrə","n.","管弦乐队"],
["s2","culture","origin","ˈɒrɪdʒɪn","n.","起源"],
["s2","culture","painting","ˈpeɪntɪŋ","n.","绘画"],
["s2","culture","performance","pəˈfɔːməns","n.","表演"],
["s2","culture","photograph","ˈfəʊtəɡrɑːf","n.","照片"],
["s2","culture","photography","fəˈtɒɡrəfi","n.","摄影"],
["s2","culture","play","pleɪ","n.","戏剧"],
["s2","culture","playwright","ˈpleɪraɪt","n.","剧作家"],
["s2","culture","poem","ˈpəʊɪm","n.","诗"],
["s2","culture","poet","ˈpəʊɪt","n.","诗人"],
["s2","culture","poetry","ˈpəʊətri","n.","诗歌"],
["s2","culture","popular","ˈpɒpjələ(r)","adj.","流行的"],
["s2","culture","portrait","ˈpɔːtreɪt","n.","肖像"],
["s2","culture","print","prɪnt","v./n.","印刷"],
["s2","culture","propaganda","ˌprɒpəˈɡændə","n.","宣传"],
["s2","culture","publication","ˌpʌblɪˈkeɪʃn","n.","出版"],
["s2","culture","publishing","ˈpʌblɪʃɪŋ","n.","出版业"],
["s2","culture","radio","ˈreɪdiəʊ","n.","广播"],
["s2","culture","reality","riˈæləti","n.","现实"],
["s2","culture","recital","rɪˈsaɪtl","n.","独奏会"],
["s2","culture","recording","rɪˈkɔːdɪŋ","n.","录音"],
["s2","culture","romance","rəʊˈmæns","n.","浪漫"],
["s2","culture","sculpture","ˈskʌlptʃə(r)","n.","雕塑"],
["s2","culture","script","skrɪpt","n.","剧本"],
["s2","culture","singer","ˈsɪŋə(r)","n.","歌手"],
["s2","culture","sketch","sketʃ","n.","素描"],
["s2","culture","soap opera","ˈsəʊp ˈɒprə","n.","肥皂剧"],
["s2","culture","stage","steɪdʒ","n.","舞台"],
["s2","culture","studio","ˈstjuːdiəʊ","n.","工作室"],
["s2","culture","style","staɪl","n.","风格"],
["s2","culture","symbol","ˈsɪmbl","n.","象征"],
["s2","culture","talent","ˈtælənt","n.","才能"],
["s2","culture","television","ˈtelɪvɪʒn","n.","电视"],
["s2","culture","theatre","ˈθɪətə(r)","n.","剧院"],
["s2","culture","tradition","trəˈdɪʃn","n.","传统"],
["s2","culture","tune","tjuːn","n.","曲调"],
["s2","culture","vintage","ˈvɪntɪdʒ","adj.","年代久远的"],
["s2","culture","writer","ˈraɪtə(r)","n.","作家"],

// ============== 城市 / 交通 CITY & TRANSPORT (~150) ==============
["s2","city","accommodation","əˌkɒməˈdeɪʃn","n.","住宿"],
["s2","city","airport","ˈeəpɔːt","n.","机场"],
["s2","city","alleyway","ˈæliweɪ","n.","小巷"],
["s2","city","apartment","əˈpɑːtmənt","n.","公寓"],
["s2","city","architecture","ˈɑːkɪtektʃə(r)","n.","建筑"],
["s2","city","avenue","ˈævənjuː","n.","大道"],
["s2","city","balcony","ˈbælkəni","n.","阳台"],
["s2","city","basement","ˈbeɪsmənt","n.","地下室"],
["s2","city","bicycle","ˈbaɪsɪkl","n.","自行车"],
["s2","city","block","blɒk","n.","街区"],
["s2","city","boulevard","ˈbuːləvɑːd","n.","林荫大道"],
["s2","city","bridge","brɪdʒ","n.","桥"],
["s2","city","building","ˈbɪldɪŋ","n.","建筑"],
["s2","city","bungalow","ˈbʌŋɡələʊ","n.","平房"],
["s2","city","bus","bʌs","n.","公共汽车"],
["s2","city","cab","kæb","n.","出租车"],
["s2","city","carriage","ˈkærɪdʒ","n.","车厢"],
["s2","city","cathedral","kəˈθiːdrəl","n.","大教堂"],
["s2","city","CBD","ˌsiː biː ˈdiː","n.","中央商务区"],
["s2","city","centre","ˈsentə(r)","n.","中心"],
["s2","city","city","ˈsɪti","n.","城市"],
["s2","city","city centre","ˈsɪti ˈsentə(r)","n.","市中心"],
["s2","city","civic","ˈsɪvɪk","adj.","市民的"],
["s2","city","commuter","kəˈmjuːtə(r)","n.","通勤者"],
["s2","city","compact","kəmˈpækt","adj.","紧凑的"],
["s2","city","congestion","kənˈdʒestʃən","n.","拥堵"],
["s2","city","construction","kənˈstrʌkʃn","n.","建设"],
["s2","city","cottage","ˈkɒtɪdʒ","n.","村舍"],
["s2","city","council","ˈkaʊnsl","n.","议会"],
["s2","city","countryside","ˈkʌntrisaɪd","n.","乡村"],
["s2","city","crossroads","ˈkrɒsrəʊdz","n.","十字路口"],
["s2","city","crowd","kraʊd","n.","人群"],
["s2","city","cyclist","ˈsaɪklɪst","n.","骑车人"],
["s2","city","densely populated","ˈdensli ˈpɒpjuleɪtɪd","adj.","人口密集的"],
["s2","city","destination","ˌdestɪˈneɪʃn","n.","目的地"],
["s2","city","district","ˈdɪstrɪkt","n.","区"],
["s2","city","downtown","ˌdaʊnˈtaʊn","n./adv.","市中心"],
["s2","city","driver","ˈdraɪvə(r)","n.","司机"],
["s2","city","dwelling","ˈdwelɪŋ","n.","住所"],
["s2","city","exhaust","ɪɡˈzɔːst","n.","废气"],
["s2","city","facility","fəˈsɪləti","n.","设施"],
["s2","city","factory","ˈfæktri","n.","工厂"],
["s2","city","fare","feə(r)","n.","车费"],
["s2","city","flat","flæt","n.","公寓"],
["s2","city","footpath","ˈfʊtpɑːθ","n.","人行道"],
["s2","city","freeway","ˈfriːweɪ","n.","高速公路"],
["s2","city","fuel","ˈfjuːəl","n.","燃料"],
["s2","city","garage","ˈɡærɑːʒ","n.","车库"],
["s2","city","garden","ˈɡɑːdn","n.","花园"],
["s2","city","gridlock","ˈɡrɪdlɒk","n.","交通堵塞"],
["s2","city","harbour","ˈhɑːbə(r)","n.","港口"],
["s2","city","highway","ˈhaɪweɪ","n.","公路"],
["s2","city","housing","ˈhaʊzɪŋ","n.","住房"],
["s2","city","infrastructure","ˈɪnfrəstrʌktʃə(r)","n.","基础设施"],
["s2","city","intersection","ˌɪntəˈsekʃn","n.","十字路口"],
["s2","city","junction","ˈdʒʌŋkʃn","n.","路口"],
["s2","city","lane","leɪn","n.","车道；小巷"],
["s2","city","layout","ˈleɪaʊt","n.","布局"],
["s2","city","lift","lɪft","n.","电梯"],
["s2","city","mansion","ˈmænʃn","n.","公馆"],
["s2","city","metropolis","məˈtrɒpəlɪs","n.","大都市"],
["s2","city","motorway","ˈməʊtəweɪ","n.","高速公路"],
["s2","city","neighbour","ˈneɪbə(r)","n.","邻居"],
["s2","city","neighbourhood","ˈneɪbəhʊd","n.","邻里"],
["s2","city","outskirts","ˈaʊtskɜːts","n.","郊区"],
["s2","city","overpass","ˈəʊvəpɑːs","n.","天桥"],
["s2","city","park","pɑːk","n.","公园"],
["s2","city","parking","ˈpɑːkɪŋ","n.","停车"],
["s2","city","passenger","ˈpæsɪndʒə(r)","n.","乘客"],
["s2","city","pavement","ˈpeɪvmənt","n.","人行道"],
["s2","city","pedestrian","pəˈdestriən","n.","行人"],
["s2","city","platform","ˈplætfɔːm","n.","站台"],
["s2","city","plaza","ˈplɑːzə","n.","广场"],
["s2","city","population density","ˌpɒpjuˈleɪʃn ˈdensəti","n.","人口密度"],
["s2","city","port","pɔːt","n.","港口"],
["s2","city","public transport","ˈpʌblɪk ˈtrænspɔːt","n.","公共交通"],
["s2","city","railway","ˈreɪlweɪ","n.","铁路"],
["s2","city","ride","raɪd","n./v.","乘坐"],
["s2","city","road","rəʊd","n.","路"],
["s2","city","roundabout","ˈraʊndəbaʊt","n.","环岛"],
["s2","city","route","ruːt","n.","路线"],
["s2","city","rural","ˈrʊərəl","adj.","农村的"],
["s2","city","rush hour","rʌʃ aʊə(r)","n.","高峰期"],
["s2","city","sidewalk","ˈsaɪdwɔːk","n.","人行道"],
["s2","city","signal","ˈsɪɡnəl","n.","信号"],
["s2","city","skyscraper","ˈskaɪskreɪpə(r)","n.","摩天楼"],
["s2","city","slum","slʌm","n.","贫民窟"],
["s2","city","smog","smɒɡ","n.","烟雾"],
["s2","city","speed limit","spiːd ˈlɪmɪt","n.","限速"],
["s2","city","square","skweə(r)","n.","广场"],
["s2","city","station","ˈsteɪʃn","n.","站"],
["s2","city","street","striːt","n.","街道"],
["s2","city","subway","ˈsʌbweɪ","n.","地铁"],
["s2","city","suburb","ˈsʌbɜːb","n.","郊区"],
["s2","city","taxi","ˈtæksi","n.","出租车"],
["s2","city","terminal","ˈtɜːmɪnl","n.","终点站"],
["s2","city","tower","ˈtaʊə(r)","n.","塔"],
["s2","city","traffic","ˈtræfɪk","n.","交通"],
["s2","city","traffic jam","ˈtræfɪk dʒæm","n.","交通堵塞"],
["s2","city","train","treɪn","n.","火车"],
["s2","city","tram","træm","n.","电车"],
["s2","city","transport","ˈtrænspɔːt","n./v.","运输"],
["s2","city","tube","tjuːb","n.","地铁"],
["s2","city","tunnel","ˈtʌnl","n.","隧道"],
["s2","city","underground","ˌʌndəˈɡraʊnd","n./adj.","地下"],
["s2","city","urban","ˈɜːbən","adj.","城市的"],
["s2","city","vehicle","ˈviːəkl","n.","车辆"],
["s2","city","village","ˈvɪlɪdʒ","n.","村庄"],
["s2","city","walkway","ˈwɔːkweɪ","n.","人行道"],
["s2","city","zone","zəʊn","n.","区域"],

// ============== 旅游 TRAVEL (~100) ==============
["s2","travel","abroad","əˈbrɔːd","adv.","在国外"],
["s2","travel","accommodation","əˌkɒməˈdeɪʃn","n.","住宿"],
["s2","travel","adventure","ədˈventʃə(r)","n.","冒险"],
["s2","travel","aisle","aɪl","n.","过道"],
["s2","travel","airline","ˈeəlaɪn","n.","航空公司"],
["s2","travel","arrival","əˈraɪvl","n.","到达"],
["s2","travel","attraction","əˈtrækʃn","n.","景点"],
["s2","travel","backpack","ˈbækpæk","n.","背包"],
["s2","travel","baggage","ˈbæɡɪdʒ","n.","行李"],
["s2","travel","beach","biːtʃ","n.","海滩"],
["s2","travel","board","bɔːd","v.","登机"],
["s2","travel","booking","ˈbʊkɪŋ","n.","预订"],
["s2","travel","boarding pass","ˈbɔːdɪŋ pɑːs","n.","登机牌"],
["s2","travel","brochure","ˈbrəʊʃə(r)","n.","小册子"],
["s2","travel","camping","ˈkæmpɪŋ","n.","露营"],
["s2","travel","canyon","ˈkænjən","n.","峡谷"],
["s2","travel","cancel","ˈkænsl","v.","取消"],
["s2","travel","capital","ˈkæpɪtl","n.","首都"],
["s2","travel","carriage","ˈkærɪdʒ","n.","车厢"],
["s2","travel","castle","ˈkɑːsl","n.","城堡"],
["s2","travel","check-in","ˈtʃek ɪn","n.","办理登机"],
["s2","travel","check out","tʃek aʊt","v.","结账退房"],
["s2","travel","climb","klaɪm","v.","攀登"],
["s2","travel","coastline","ˈkəʊstlaɪn","n.","海岸线"],
["s2","travel","continent","ˈkɒntɪnənt","n.","大陆"],
["s2","travel","cruise","kruːz","n.","巡游"],
["s2","travel","currency","ˈkʌrənsi","n.","货币"],
["s2","travel","customs","ˈkʌstəmz","n.","海关"],
["s2","travel","delay","dɪˈleɪ","n./v.","延误"],
["s2","travel","departure","dɪˈpɑːtʃə(r)","n.","出发"],
["s2","travel","destination","ˌdestɪˈneɪʃn","n.","目的地"],
["s2","travel","detour","ˈdiːtʊə(r)","n.","绕路"],
["s2","travel","domestic","dəˈmestɪk","adj.","国内的"],
["s2","travel","duty-free","ˌdjuːti ˈfriː","adj.","免税的"],
["s2","travel","economy class","ɪˈkɒnəmi klɑːs","n.","经济舱"],
["s2","travel","embark","ɪmˈbɑːk","v.","出发"],
["s2","travel","excursion","ɪkˈskɜːʃn","n.","短途旅行"],
["s2","travel","explore","ɪkˈsplɔː(r)","v.","探索"],
["s2","travel","fare","feə(r)","n.","车费"],
["s2","travel","flight","flaɪt","n.","航班"],
["s2","travel","foreign","ˈfɒrən","adj.","外国的"],
["s2","travel","gateway","ˈɡeɪtweɪ","n.","通道"],
["s2","travel","glacier","ˈɡlæsiə(r)","n.","冰川"],
["s2","travel","guide","ɡaɪd","n.","导游"],
["s2","travel","guidebook","ˈɡaɪdbʊk","n.","指南"],
["s2","travel","hike","haɪk","v./n.","徒步"],
["s2","travel","historical site","hɪˈstɒrɪkl saɪt","n.","历史古迹"],
["s2","travel","hostel","ˈhɒstl","n.","旅社"],
["s2","travel","hotel","həʊˈtel","n.","酒店"],
["s2","travel","insurance","ɪnˈʃʊərəns","n.","保险"],
["s2","travel","international","ˌɪntəˈnæʃnəl","adj.","国际的"],
["s2","travel","itinerary","aɪˈtɪnərəri","n.","行程"],
["s2","travel","journey","ˈdʒɜːni","n.","旅程"],
["s2","travel","jet lag","dʒet læɡ","n.","时差"],
["s2","travel","landmark","ˈlændmɑːk","n.","地标"],
["s2","travel","landscape","ˈlændskeɪp","n.","风景"],
["s2","travel","local","ˈləʊkl","adj.","当地的"],
["s2","travel","luggage","ˈlʌɡɪdʒ","n.","行李"],
["s2","travel","mountain","ˈmaʊntən","n.","山"],
["s2","travel","monument","ˈmɒnjumənt","n.","纪念碑"],
["s2","travel","oasis","əʊˈeɪsɪs","n.","绿洲"],
["s2","travel","ocean","ˈəʊʃn","n.","海洋"],
["s2","travel","one-way ticket","wʌn weɪ ˈtɪkɪt","n.","单程票"],
["s2","travel","overseas","ˌəʊvəˈsiːz","adv.","海外"],
["s2","travel","package","ˈpækɪdʒ","n.","旅游套餐"],
["s2","travel","passport","ˈpɑːspɔːt","n.","护照"],
["s2","travel","peninsula","pəˈnɪnsjələ","n.","半岛"],
["s2","travel","postcard","ˈpəʊstkɑːd","n.","明信片"],
["s2","travel","port","pɔːt","n.","港口"],
["s2","travel","reservation","ˌrezəˈveɪʃn","n.","预订"],
["s2","travel","resort","rɪˈzɔːt","n.","度假胜地"],
["s2","travel","return ticket","rɪˈtɜːn ˈtɪkɪt","n.","往返票"],
["s2","travel","route","ruːt","n.","路线"],
["s2","travel","scenery","ˈsiːnəri","n.","风景"],
["s2","travel","sightseeing","ˈsaɪtsiːɪŋ","n.","观光"],
["s2","travel","souvenir","ˌsuːvəˈnɪə(r)","n.","纪念品"],
["s2","travel","stopover","ˈstɒpəʊvə(r)","n.","中转停留"],
["s2","travel","suburb","ˈsʌbɜːb","n.","郊区"],
["s2","travel","suitcase","ˈsuːtkeɪs","n.","行李箱"],
["s2","travel","tourism","ˈtʊərɪzəm","n.","旅游业"],
["s2","travel","tourist","ˈtʊərɪst","n.","游客"],
["s2","travel","trail","treɪl","n.","小径"],
["s2","travel","transit","ˈtrænzɪt","n.","中转"],
["s2","travel","travel agency","ˈtrævl ˈeɪdʒənsi","n.","旅行社"],
["s2","travel","trip","trɪp","n.","旅行"],
["s2","travel","valley","ˈvæli","n.","山谷"],
["s2","travel","visa","ˈviːzə","n.","签证"],
["s2","travel","voyage","ˈvɔɪɪdʒ","n.","航行"],
["s2","travel","wildlife","ˈwaɪldlaɪf","n.","野生动物"],

]);
