// STAGE II · 主题词 (Education/Environment/Technology/Health)
window.VOCAB = (window.VOCAB || []).concat([

// ============== 教育 EDUCATION (~200) ==============
["s2","edu","academic","ˌækəˈdemɪk","adj.","学术的"],
["s2","edu","admission","ədˈmɪʃn","n.","录取"],
["s2","edu","apprenticeship","əˈprentɪʃɪp","n.","学徒期"],
["s2","edu","assessment","əˈsesmənt","n.","评估"],
["s2","edu","assignment","əˈsaɪnmənt","n.","作业"],
["s2","edu","attendance","əˈtendəns","n.","出勤"],
["s2","edu","bachelor","ˈbætʃələ(r)","n.","学士"],
["s2","edu","boarding school","ˈbɔːdɪŋ skuːl","n.","寄宿学校"],
["s2","edu","campus","ˈkæmpəs","n.","校园"],
["s2","edu","certificate","səˈtɪfɪkət","n.","证书"],
["s2","edu","coeducation","ˌkəʊedʒuˈkeɪʃn","n.","男女同校"],
["s2","edu","compulsory","kəmˈpʌlsəri","adj.","义务的；强制的"],
["s2","edu","comprehensive","ˌkɒmprɪˈhensɪv","adj.","综合的"],
["s2","edu","coursework","ˈkɔːswɜːk","n.","平时作业"],
["s2","edu","cram","kræm","v.","填鸭式学习"],
["s2","edu","credit","ˈkredɪt","n.","学分"],
["s2","edu","curriculum","kəˈrɪkjələm","n.","课程体系","A more flexible <b>curriculum</b> would allow students to follow their own interests.","C14 R"],
["s2","edu","degree","dɪˈɡriː","n.","学位"],
["s2","edu","department","dɪˈpɑːtmənt","n.","系；部门"],
["s2","edu","dictionary","ˈdɪkʃənri","n.","词典"],
["s2","edu","diploma","dɪˈpləʊmə","n.","文凭"],
["s2","edu","discipline","ˈdɪsəplɪn","n.","学科；纪律","Linguistics is a relatively young <b>discipline</b>.","C10 R"],
["s2","edu","dissertation","ˌdɪsəˈteɪʃn","n.","论文（硕博）"],
["s2","edu","distance learning","ˈdɪstəns ˈlɜːnɪŋ","n.","远程学习"],
["s2","edu","drop out","drɒp aʊt","v.","辍学"],
["s2","edu","educate","ˈedʒukeɪt","v.","教育"],
["s2","edu","elective","ɪˈlektɪv","adj./n.","选修的；选修课"],
["s2","edu","enroll","ɪnˈrəʊl","v.","注册"],
["s2","edu","essay","ˈeseɪ","n.","论文"],
["s2","edu","exam","ɪɡˈzæm","n.","考试"],
["s2","edu","extracurricular","ˌekstrəkəˈrɪkjələ(r)","adj.","课外的"],
["s2","edu","faculty","ˈfækəlti","n.","系；学院；能力"],
["s2","edu","fee","fiː","n.","费用"],
["s2","edu","graduate","ˈɡrædʒuət","n./v.","毕业生；毕业"],
["s2","edu","grade","ɡreɪd","n.","年级；成绩"],
["s2","edu","grant","ɡrɑːnt","n.","拨款；助学金"],
["s2","edu","headmaster","ˌhedˈmɑːstə(r)","n.","校长"],
["s2","edu","higher education","ˈhaɪə(r) ˌedʒuˈkeɪʃn","n.","高等教育"],
["s2","edu","homework","ˈhəʊmwɜːk","n.","家庭作业"],
["s2","edu","induction","ɪnˈdʌkʃn","n.","入学指导"],
["s2","edu","institution","ˌɪnstɪˈtjuːʃn","n.","机构"],
["s2","edu","instruction","ɪnˈstrʌkʃn","n.","指导"],
["s2","edu","intellectual","ˌɪntəˈlektʃuəl","adj.","智力的","Reading widely stimulates <b>intellectual</b> curiosity.","C12 R"],
["s2","edu","interactive","ˌɪntərˈæktɪv","adj.","互动的"],
["s2","edu","kindergarten","ˈkɪndəɡɑːtn","n.","幼儿园"],
["s2","edu","lecture","ˈlektʃə(r)","n.","讲座"],
["s2","edu","librarian","laɪˈbreəriən","n.","图书馆员"],
["s2","edu","library","ˈlaɪbrəri","n.","图书馆"],
["s2","edu","literacy","ˈlɪtərəsi","n.","读写能力","Adult <b>literacy</b> rates have improved dramatically.","C11 R"],
["s2","edu","major","ˈmeɪdʒə(r)","n.","专业"],
["s2","edu","memorise","ˈmeməraɪz","v.","记忆"],
["s2","edu","module","ˈmɒdjuːl","n.","课程单元"],
["s2","edu","motivation","ˌməʊtɪˈveɪʃn","n.","动机"],
["s2","edu","nursery","ˈnɜːsəri","n.","托儿所"],
["s2","edu","optional","ˈɒpʃənl","adj.","选修的"],
["s2","edu","peer","pɪə(r)","n.","同龄人"],
["s2","edu","plagiarism","ˈpleɪdʒərɪzəm","n.","剽窃"],
["s2","edu","postgraduate","ˌpəʊstˈɡrædʒuət","n.","研究生"],
["s2","edu","preschool","ˈpriːskuːl","n.","学前"],
["s2","edu","primary school","ˈpraɪməri skuːl","n.","小学"],
["s2","edu","principal","ˈprɪnsəpl","n.","校长"],
["s2","edu","private school","ˈpraɪvət skuːl","n.","私立学校"],
["s2","edu","public school","ˈpʌblɪk skuːl","n.","公立学校"],
["s2","edu","punish","ˈpʌnɪʃ","v.","惩罚"],
["s2","edu","pupil","ˈpjuːpl","n.","小学生"],
["s2","edu","qualification","ˌkwɒlɪfɪˈkeɪʃn","n.","资格"],
["s2","edu","quiz","kwɪz","n.","小测验"],
["s2","edu","refectory","rɪˈfektri","n.","食堂"],
["s2","edu","registration","ˌredʒɪˈstreɪʃn","n.","注册"],
["s2","edu","required","rɪˈkwaɪəd","adj.","必修的"],
["s2","edu","research","rɪˈsɜːtʃ","n.","研究"],
["s2","edu","scholarship","ˈskɒləʃɪp","n.","奖学金","She won a full <b>scholarship</b> to study medicine.","C9 L"],
["s2","edu","secondary school","ˈsekəndri skuːl","n.","中学"],
["s2","edu","semester","sɪˈmestə(r)","n.","学期"],
["s2","edu","seminar","ˈsemɪnɑː(r)","n.","研讨课"],
["s2","edu","skill","skɪl","n.","技能"],
["s2","edu","specialise","ˈspeʃəlaɪz","v.","专攻"],
["s2","edu","staff","stɑːf","n.","职工"],
["s2","edu","student","ˈstjuːdnt","n.","学生"],
["s2","edu","study","ˈstʌdi","n./v.","学习"],
["s2","edu","subject","ˈsʌbdʒɪkt","n.","科目"],
["s2","edu","supervisor","ˈsuːpəvaɪzə(r)","n.","导师"],
["s2","edu","syllabus","ˈsɪləbəs","n.","教学大纲"],
["s2","edu","take notes","teɪk nəʊts","v.","记笔记"],
["s2","edu","teach","tiːtʃ","v.","教"],
["s2","edu","term","tɜːm","n.","学期"],
["s2","edu","textbook","ˈtekstbʊk","n.","教科书"],
["s2","edu","theme","θiːm","n.","主题"],
["s2","edu","thesis","ˈθiːsɪs","n.","论文"],
["s2","edu","timetable","ˈtaɪmteɪbl","n.","时间表"],
["s2","edu","tuition","tjuˈɪʃn","n.","学费","Many students struggle to pay rising <b>tuition</b> fees.","C13 L S3"],
["s2","edu","tutor","ˈtjuːtə(r)","n.","导师"],
["s2","edu","undergraduate","ˌʌndəˈɡrædʒuət","n.","本科生"],
["s2","edu","university","ˌjuːnɪˈvɜːsəti","n.","大学"],
["s2","edu","vocabulary","vəˈkæbjələri","n.","词汇"],
["s2","edu","vocational","vəʊˈkeɪʃənl","adj.","职业的","<b>Vocational</b> training prepares school-leavers for specific trades.","BC W2"],
["s2","edu","workshop","ˈwɜːkʃɒp","n.","研讨会"],
["s2","edu","cognitive","ˈkɒɡnətɪv","adj.","认知的"],
["s2","edu","creative","kriˈeɪtɪv","adj.","创造性的"],
["s2","edu","educational","ˌedʒuˈkeɪʃənl","adj.","教育的"],
["s2","edu","gifted","ˈɡɪftɪd","adj.","有天赋的"],
["s2","edu","interactive","ˌɪntərˈæktɪv","adj.","互动的"],
["s2","edu","talented","ˈtæləntɪd","adj.","有才华的"],
["s2","edu","willing","ˈwɪlɪŋ","adj.","愿意的"],
["s2","edu","attainment","əˈteɪnmənt","n.","成就；学业成就"],
["s2","edu","aptitude","ˈæptɪtjuːd","n.","天赋"],
["s2","edu","blackboard","ˈblækbɔːd","n.","黑板"],
["s2","edu","whiteboard","ˈwaɪtbɔːd","n.","白板"],
["s2","edu","chalk","tʃɔːk","n.","粉笔"],
["s2","edu","crayon","ˈkreɪən","n.","蜡笔"],
["s2","edu","headteacher","ˌhedˈtiːtʃə(r)","n.","校长"],
["s2","edu","headmaster","ˌhedˈmɑːstə(r)","n.","男校长"],
["s2","edu","mentor","ˈmentɔː(r)","n.","导师"],
["s2","edu","oral","ˈɔːrəl","adj.","口头的"],
["s2","edu","outcome-based","ˈaʊtkʌm beɪst","adj.","结果导向的"],
["s2","edu","panel","ˈpænl","n.","专家组"],
["s2","edu","passive","ˈpæsɪv","adj.","被动的"],
["s2","edu","placement","ˈpleɪsmənt","n.","实习；安置"],
["s2","edu","portfolio","pɔːtˈfəʊliəʊ","n.","作品集"],
["s2","edu","practical","ˈpræktɪkl","adj./n.","实践的；实践课"],
["s2","edu","preliminary","prɪˈlɪmɪnəri","adj.","初步的"],
["s2","edu","prerequisite","ˌpriːˈrekwəzɪt","n.","先决条件"],
["s2","edu","procrastinate","prəˈkræstɪneɪt","v.","拖延"],
["s2","edu","proficiency","prəˈfɪʃnsi","n.","熟练程度"],
["s2","edu","prospectus","prəˈspektəs","n.","招生简章"],
["s2","edu","reasoning","ˈriːznɪŋ","n.","推理"],
["s2","edu","recess","rɪˈses","n.","课间休息"],
["s2","edu","revise","rɪˈvaɪz","v.","复习；修改"],
["s2","edu","rote","rəʊt","n.","死记硬背"],
["s2","edu","sabbatical","səˈbætɪkl","n.","学术休假"],
["s2","edu","seminar","ˈsemɪnɑː(r)","n.","研讨会"],
["s2","edu","skim","skɪm","v.","略读"],
["s2","edu","slogan","ˈsləʊɡən","n.","标语"],
["s2","edu","sociable","ˈsəʊʃəbl","adj.","善社交的"],
["s2","edu","sophomore","ˈsɒfəmɔː(r)","n.","大二学生"],
["s2","edu","spelling","ˈspelɪŋ","n.","拼写"],
["s2","edu","structured","ˈstrʌktʃəd","adj.","结构化的"],
["s2","edu","substitute","ˈsʌbstɪtjuːt","n.","代课老师"],
["s2","edu","syllabus","ˈsɪləbəs","n.","教学大纲"],
["s2","edu","take up","teɪk ʌp","v.","开始从事"],
["s2","edu","term paper","tɜːm ˈpeɪpə(r)","n.","学期论文"],
["s2","edu","testimony","ˈtestɪməni","n.","证词；证明"],
["s2","edu","theoretical","ˌθɪəˈretɪkl","adj.","理论的"],
["s2","edu","tutorial","tjuˈtɔːriəl","n.","辅导"],
["s2","edu","work placement","wɜːk ˈpleɪsmənt","n.","工作实习"],

// ============== 环境 ENVIRONMENT (~200) ==============
["s2","env","absorb","əbˈzɔːb","v.","吸收"],
["s2","env","acid rain","ˈæsɪd reɪn","n.","酸雨"],
["s2","env","aerosol","ˈeərəsɒl","n.","气溶胶"],
["s2","env","afforestation","əˌfɒrɪˈsteɪʃn","n.","植林造林"],
["s2","env","agriculture","ˈæɡrɪkʌltʃə(r)","n.","农业"],
["s2","env","atmosphere","ˈætməsfɪə(r)","n.","大气"],
["s2","env","barren","ˈbærən","adj.","贫瘠的"],
["s2","env","biodegradable","ˌbaɪəʊdɪˈɡreɪdəbl","adj.","可生物降解的"],
["s2","env","biodiversity","ˌbaɪəʊdaɪˈvɜːsəti","n.","生物多样性","Coral reefs support an extraordinary level of <b>biodiversity</b>.","C15 R"],
["s2","env","biome","ˈbaɪəʊm","n.","生物群落"],
["s2","env","carbon dioxide","ˌkɑːbən daɪˈɒksaɪd","n.","二氧化碳"],
["s2","env","carbon footprint","ˈkɑːbən ˈfʊtprɪnt","n.","碳足迹"],
["s2","env","catastrophe","kəˈtæstrəfi","n.","灾难"],
["s2","env","chemical","ˈkemɪkl","n./adj.","化学品；化学的"],
["s2","env","climate","ˈklaɪmət","n.","气候"],
["s2","env","coal","kəʊl","n.","煤"],
["s2","env","conservation","ˌkɒnsəˈveɪʃn","n.","保护","Wildlife <b>conservation</b> efforts have brought several species back from the brink.","C13 R"],
["s2","env","contaminate","kənˈtæmɪneɪt","v.","污染","Agricultural runoff has <b>contaminated</b> several local rivers.","C12 R"],
["s2","env","crop","krɒp","n.","作物"],
["s2","env","crude oil","kruːd ɔɪl","n.","原油"],
["s2","env","damage","ˈdæmɪdʒ","v./n.","破坏"],
["s2","env","deforestation","ˌdiːˌfɒrɪˈsteɪʃn","n.","森林砍伐","Tropical <b>deforestation</b> accounts for 12% of global emissions.","C10 R"],
["s2","env","degradation","ˌdeɡrəˈdeɪʃn","n.","退化"],
["s2","env","desert","ˈdezət","n./v.","沙漠；遗弃"],
["s2","env","desertification","dɪˌzɜːtɪfɪˈkeɪʃn","n.","沙漠化"],
["s2","env","destroy","dɪˈstrɔɪ","v.","破坏"],
["s2","env","discharge","dɪsˈtʃɑːdʒ","v./n.","排放"],
["s2","env","disposable","dɪˈspəʊzəbl","adj.","一次性的"],
["s2","env","drought","draʊt","n.","干旱"],
["s2","env","dwelling","ˈdwelɪŋ","n.","住所"],
["s2","env","earthquake","ˈɜːθkweɪk","n.","地震"],
["s2","env","ecology","iˈkɒlədʒi","n.","生态学"],
["s2","env","ecosystem","ˈiːkəʊsɪstəm","n.","生态系统","Invasive species can disrupt fragile <b>ecosystems</b>.","C13 L"],
["s2","env","emission","ɪˈmɪʃn","n.","排放","Government policy aims to halve carbon <b>emissions</b> by 2030.","C14 R"],
["s2","env","endangered","ɪnˈdeɪndʒəd","adj.","濒危的"],
["s2","env","energy","ˈenədʒi","n.","能源"],
["s2","env","environment","ɪnˈvaɪrənmənt","n.","环境"],
["s2","env","erosion","ɪˈrəʊʒn","n.","侵蚀"],
["s2","env","exhaust","ɪɡˈzɔːst","n./v.","废气；耗尽"],
["s2","env","extinct","ɪkˈstɪŋkt","adj.","灭绝的"],
["s2","env","fauna","ˈfɔːnə","n.","动物群"],
["s2","env","fertile","ˈfɜːtaɪl","adj.","肥沃的"],
["s2","env","flood","flʌd","n./v.","洪水"],
["s2","env","flora","ˈflɔːrə","n.","植物群"],
["s2","env","fossil fuel","ˈfɒsl ˈfjuːəl","n.","化石燃料"],
["s2","env","freshwater","ˈfreʃwɔːtə(r)","n.","淡水"],
["s2","env","fume","fjuːm","n.","烟雾"],
["s2","env","garbage","ˈɡɑːbɪdʒ","n.","垃圾"],
["s2","env","geothermal","ˌdʒiːəʊˈθɜːml","adj.","地热的"],
["s2","env","glacier","ˈɡlæsiə(r)","n.","冰川"],
["s2","env","global warming","ˌɡləʊbl ˈwɔːmɪŋ","n.","全球变暖"],
["s2","env","grassland","ˈɡrɑːslænd","n.","草原"],
["s2","env","greenhouse","ˈɡriːnhaʊs","n.","温室"],
["s2","env","habitat","ˈhæbɪtæt","n.","栖息地"],
["s2","env","hazard","ˈhæzəd","n.","危险"],
["s2","env","hydropower","ˈhaɪdrəʊpaʊə(r)","n.","水力发电"],
["s2","env","ice cap","aɪs kæp","n.","冰盖"],
["s2","env","incinerate","ɪnˈsɪnəreɪt","v.","焚化"],
["s2","env","invasive","ɪnˈveɪsɪv","adj.","入侵的"],
["s2","env","irrigate","ˈɪrɪɡeɪt","v.","灌溉"],
["s2","env","landfill","ˈlændfɪl","n.","垃圾填埋场"],
["s2","env","landscape","ˈlændskeɪp","n.","景观"],
["s2","env","litter","ˈlɪtə(r)","n.","乱扔的垃圾"],
["s2","env","manure","məˈnjʊə(r)","n.","肥料"],
["s2","env","marine","məˈriːn","adj.","海洋的"],
["s2","env","melt","melt","v.","融化"],
["s2","env","methane","ˈmiːθeɪn","n.","甲烷"],
["s2","env","mineral","ˈmɪnərəl","n.","矿物"],
["s2","env","natural resources","ˈnætʃrəl rɪˈsɔːsɪz","n.","自然资源"],
["s2","env","nuclear","ˈnjuːkliə(r)","adj.","核的"],
["s2","env","ocean","ˈəʊʃn","n.","海洋"],
["s2","env","ore","ɔː(r)","n.","矿石"],
["s2","env","organic","ɔːˈɡænɪk","adj.","有机的"],
["s2","env","pesticide","ˈpestɪsaɪd","n.","农药"],
["s2","env","petroleum","pəˈtrəʊliəm","n.","石油"],
["s2","env","planet","ˈplænɪt","n.","行星"],
["s2","env","plastic","ˈplæstɪk","n.","塑料"],
["s2","env","polar","ˈpəʊlə(r)","adj.","极地的"],
["s2","env","pollutant","pəˈluːtənt","n.","污染物"],
["s2","env","pollute","pəˈluːt","v.","污染"],
["s2","env","pollution","pəˈluːʃn","n.","污染"],
["s2","env","population","ˌpɒpjuˈleɪʃn","n.","种群；人口"],
["s2","env","preserve","prɪˈzɜːv","v.","保存"],
["s2","env","rainforest","ˈreɪnfɒrɪst","n.","雨林"],
["s2","env","recycle","ˌriːˈsaɪkl","v.","回收"],
["s2","env","reforestation","ˌriːˌfɒrɪˈsteɪʃn","n.","重新造林"],
["s2","env","renewable","rɪˈnjuːəbl","adj.","可再生的","Solar and wind power are the fastest-growing <b>renewable</b> energy sources.","C11 W1"],
["s2","env","reservoir","ˈrezəvwɑː(r)","n.","水库"],
["s2","env","reuse","ˌriːˈjuːz","v.","重复使用"],
["s2","env","sewage","ˈsuːɪdʒ","n.","污水"],
["s2","env","smog","smɒɡ","n.","烟雾"],
["s2","env","solar","ˈsəʊlə(r)","adj.","太阳能的"],
["s2","env","species","ˈspiːʃiːz","n.","物种"],
["s2","env","sustainable","səˈsteɪnəbl","adj.","可持续的","We urgently need a <b>sustainable</b> alternative to fossil fuels.","C12 W2"],
["s2","env","temperature","ˈtemprətʃə(r)","n.","温度"],
["s2","env","thermal","ˈθɜːml","adj.","热的"],
["s2","env","tide","taɪd","n.","潮汐"],
["s2","env","timber","ˈtɪmbə(r)","n.","木材"],
["s2","env","toxic","ˈtɒksɪk","adj.","有毒的"],
["s2","env","tropical","ˈtrɒpɪkl","adj.","热带的"],
["s2","env","tsunami","tsuːˈnɑːmi","n.","海啸"],
["s2","env","ultraviolet","ˌʌltrəˈvaɪələt","adj.","紫外线的"],
["s2","env","vegetation","ˌvedʒəˈteɪʃn","n.","植被"],
["s2","env","volcano","vɒlˈkeɪnəʊ","n.","火山"],
["s2","env","waste","weɪst","n./v.","废物；浪费"],
["s2","env","wildlife","ˈwaɪldlaɪf","n.","野生动物"],
["s2","env","wind farm","wɪnd fɑːm","n.","风力发电厂"],

// ============== 科技 TECHNOLOGY (~180) ==============
["s2","tech","access","ˈækses","n./v.","访问"],
["s2","tech","algorithm","ˈælɡərɪðəm","n.","算法","Recommendation <b>algorithms</b> shape what we see online.","BC W2"],
["s2","tech","app","æp","n.","应用程序"],
["s2","tech","application","ˌæplɪˈkeɪʃn","n.","应用"],
["s2","tech","artificial","ˌɑːtɪˈfɪʃl","adj.","人工的"],
["s2","tech","artificial intelligence","ˌɑːtɪˈfɪʃl ɪnˈtelɪdʒəns","n.","人工智能","<b>Artificial intelligence</b> is increasingly used to diagnose disease.","C16 R"],
["s2","tech","automate","ˈɔːtəmeɪt","v.","使自动化","Many routine tasks have now been <b>automated</b>.","C15 R"],
["s2","tech","automation","ˌɔːtəˈmeɪʃn","n.","自动化"],
["s2","tech","autonomous","ɔːˈtɒnəməs","adj.","自主的"],
["s2","tech","bandwidth","ˈbændwɪdθ","n.","带宽"],
["s2","tech","biotechnology","ˌbaɪəʊtekˈnɒlədʒi","n.","生物技术"],
["s2","tech","breakthrough","ˈbreɪkθruː","n.","突破"],
["s2","tech","browser","ˈbraʊzə(r)","n.","浏览器"],
["s2","tech","circuit","ˈsɜːkɪt","n.","电路"],
["s2","tech","clone","kləʊn","n./v.","克隆"],
["s2","tech","cloud","klaʊd","n.","云"],
["s2","tech","code","kəʊd","n./v.","代码；编程"],
["s2","tech","computer","kəmˈpjuːtə(r)","n.","电脑"],
["s2","tech","connect","kəˈnekt","v.","连接"],
["s2","tech","cybersecurity","ˌsaɪbəsɪˈkjʊərəti","n.","网络安全"],
["s2","tech","data","ˈdeɪtə","n.","数据"],
["s2","tech","database","ˈdeɪtəbeɪs","n.","数据库"],
["s2","tech","desktop","ˈdesktɒp","n.","台式机"],
["s2","tech","device","dɪˈvaɪs","n.","设备","Most adults now own at least three internet-connected <b>devices</b>.","C13 L"],
["s2","tech","digital","ˈdɪdʒɪtl","adj.","数字的"],
["s2","tech","download","ˌdaʊnˈləʊd","v.","下载"],
["s2","tech","drone","drəʊn","n.","无人机"],
["s2","tech","e-commerce","ˈiː kɒmɜːs","n.","电子商务"],
["s2","tech","electronic","ɪˌlekˈtrɒnɪk","adj.","电子的"],
["s2","tech","email","ˈiːmeɪl","n.","电子邮件"],
["s2","tech","encrypt","ɪnˈkrɪpt","v.","加密"],
["s2","tech","engine","ˈendʒɪn","n.","引擎"],
["s2","tech","equipment","ɪˈkwɪpmənt","n.","设备"],
["s2","tech","evolve","ɪˈvɒlv","v.","演化"],
["s2","tech","experimental","ɪkˌsperɪˈmentl","adj.","实验性的"],
["s2","tech","facility","fəˈsɪləti","n.","设施"],
["s2","tech","file","faɪl","n.","文件"],
["s2","tech","firewall","ˈfaɪəwɔːl","n.","防火墙"],
["s2","tech","function","ˈfʌŋkʃn","n./v.","功能；运转"],
["s2","tech","gadget","ˈɡædʒɪt","n.","小工具"],
["s2","tech","genetic","dʒəˈnetɪk","adj.","基因的"],
["s2","tech","hack","hæk","v./n.","黑客攻击"],
["s2","tech","hardware","ˈhɑːdweə(r)","n.","硬件"],
["s2","tech","high-tech","ˌhaɪˈtek","adj.","高科技的"],
["s2","tech","industrial","ɪnˈdʌstriəl","adj.","工业的"],
["s2","tech","information","ˌɪnfəˈmeɪʃn","n.","信息"],
["s2","tech","innovate","ˈɪnəveɪt","v.","创新"],
["s2","tech","innovation","ˌɪnəˈveɪʃn","n.","创新","Technological <b>innovation</b> has reshaped almost every industry.","C14 W2"],
["s2","tech","input","ˈɪnpʊt","n./v.","输入"],
["s2","tech","install","ɪnˈstɔːl","v.","安装"],
["s2","tech","interface","ˈɪntəfeɪs","n.","界面"],
["s2","tech","internet","ˈɪntənet","n.","互联网"],
["s2","tech","invention","ɪnˈvenʃn","n.","发明"],
["s2","tech","invent","ɪnˈvent","v.","发明"],
["s2","tech","keyboard","ˈkiːbɔːd","n.","键盘"],
["s2","tech","laptop","ˈlæptɒp","n.","笔记本电脑"],
["s2","tech","laser","ˈleɪzə(r)","n.","激光"],
["s2","tech","launch","lɔːntʃ","v.","发射；启动"],
["s2","tech","machine","məˈʃiːn","n.","机器"],
["s2","tech","machinery","məˈʃiːnəri","n.","机器；机械"],
["s2","tech","mainframe","ˈmeɪnfreɪm","n.","大型机"],
["s2","tech","malfunction","ˌmælˈfʌŋkʃn","n.","故障"],
["s2","tech","mechanical","məˈkænɪkl","adj.","机械的"],
["s2","tech","media","ˈmiːdiə","n.","媒体"],
["s2","tech","memory","ˈmeməri","n.","存储；记忆"],
["s2","tech","mobile","ˈməʊbaɪl","adj./n.","移动的；手机"],
["s2","tech","monitor","ˈmɒnɪtə(r)","n./v.","显示器；监控"],
["s2","tech","nanotechnology","ˌnænəʊtekˈnɒlədʒi","n.","纳米技术"],
["s2","tech","navigate","ˈnævɪɡeɪt","v.","导航"],
["s2","tech","network","ˈnetwɜːk","n.","网络"],
["s2","tech","obsolete","ˈɒbsəliːt","adj.","过时的"],
["s2","tech","online","ˌɒnˈlaɪn","adj./adv.","在线"],
["s2","tech","operating system","ˈɒpəreɪtɪŋ ˈsɪstəm","n.","操作系统"],
["s2","tech","output","ˈaʊtpʊt","n.","输出"],
["s2","tech","password","ˈpɑːswɜːd","n.","密码"],
["s2","tech","platform","ˈplætfɔːm","n.","平台"],
["s2","tech","privacy","ˈprɪvəsi","n.","隐私"],
["s2","tech","processor","ˈprəʊsesə(r)","n.","处理器"],
["s2","tech","program","ˈprəʊɡræm","n./v.","程序"],
["s2","tech","programmer","ˈprəʊɡræmə(r)","n.","程序员"],
["s2","tech","prototype","ˈprəʊtətaɪp","n.","原型"],
["s2","tech","remote","rɪˈməʊt","adj.","遥控的；远程的"],
["s2","tech","render","ˈrendə(r)","v.","渲染"],
["s2","tech","robot","ˈrəʊbɒt","n.","机器人"],
["s2","tech","router","ˈruːtə(r)","n.","路由器"],
["s2","tech","scanner","ˈskænə(r)","n.","扫描仪"],
["s2","tech","screen","skriːn","n.","屏幕"],
["s2","tech","search engine","sɜːtʃ ˈendʒɪn","n.","搜索引擎"],
["s2","tech","sensor","ˈsensə(r)","n.","传感器"],
["s2","tech","server","ˈsɜːvə(r)","n.","服务器"],
["s2","tech","simulate","ˈsɪmjuleɪt","v.","模拟"],
["s2","tech","smartphone","ˈsmɑːtfəʊn","n.","智能手机"],
["s2","tech","social media","ˈsəʊʃl ˈmiːdiə","n.","社交媒体"],
["s2","tech","software","ˈsɒftweə(r)","n.","软件"],
["s2","tech","surveillance","sɜːˈveɪləns","n.","监视","Widespread CCTV <b>surveillance</b> raises serious concerns about privacy.","C12 W2"],
["s2","tech","tablet","ˈtæblət","n.","平板电脑"],
["s2","tech","technical","ˈteknɪkl","adj.","技术的"],
["s2","tech","technological","ˌteknəˈlɒdʒɪkl","adj.","技术的"],
["s2","tech","technology","tekˈnɒlədʒi","n.","技术"],
["s2","tech","telecommunication","ˌtelɪkəˌmjuːnɪˈkeɪʃn","n.","电信"],
["s2","tech","transmit","trænzˈmɪt","v.","传输"],
["s2","tech","trend","trend","n.","趋势"],
["s2","tech","update","ˌʌpˈdeɪt","v./n.","更新"],
["s2","tech","upload","ˌʌpˈləʊd","v.","上传"],
["s2","tech","upgrade","ˌʌpˈɡreɪd","v.","升级"],
["s2","tech","username","ˈjuːzəneɪm","n.","用户名"],
["s2","tech","virtual","ˈvɜːtʃuəl","adj.","虚拟的"],
["s2","tech","virus","ˈvaɪrəs","n.","病毒"],
["s2","tech","website","ˈwebsaɪt","n.","网站"],
["s2","tech","wireless","ˈwaɪələs","adj.","无线的"],

// ============== 健康 HEALTH (~180) ==============
["s2","health","abuse","əˈbjuːz","n./v.","滥用"],
["s2","health","addiction","əˈdɪkʃn","n.","上瘾"],
["s2","health","allergy","ˈælədʒi","n.","过敏"],
["s2","health","ambulance","ˈæmbjələns","n.","救护车"],
["s2","health","anaesthetic","ˌænəsˈθetɪk","n.","麻醉剂"],
["s2","health","antibiotic","ˌæntibaɪˈɒtɪk","n.","抗生素"],
["s2","health","anxiety","æŋˈzaɪəti","n.","焦虑"],
["s2","health","appetite","ˈæpɪtaɪt","n.","食欲"],
["s2","health","artery","ˈɑːtəri","n.","动脉"],
["s2","health","asthma","ˈæsmə","n.","哮喘"],
["s2","health","balance","ˈbæləns","n./v.","平衡"],
["s2","health","bandage","ˈbændɪdʒ","n.","绷带"],
["s2","health","blood pressure","blʌd ˈpreʃə(r)","n.","血压"],
["s2","health","brain","breɪn","n.","脑"],
["s2","health","breath","breθ","n.","呼吸"],
["s2","health","calorie","ˈkæləri","n.","卡路里"],
["s2","health","cancer","ˈkænsə(r)","n.","癌症"],
["s2","health","cardiovascular","ˌkɑːdiəʊˈvæskjələ(r)","adj.","心血管的"],
["s2","health","cardiac","ˈkɑːdiæk","adj.","心脏的"],
["s2","health","cell","sel","n.","细胞"],
["s2","health","cholesterol","kəˈlestərɒl","n.","胆固醇"],
["s2","health","chronic","ˈkrɒnɪk","adj.","慢性的","Sedentary lifestyles are linked to a range of <b>chronic</b> illnesses.","C12 R"],
["s2","health","clinic","ˈklɪnɪk","n.","诊所"],
["s2","health","cognitive","ˈkɒɡnətɪv","adj.","认知的"],
["s2","health","contagious","kənˈteɪdʒəs","adj.","传染的"],
["s2","health","cure","kjʊə(r)","v./n.","治愈"],
["s2","health","dementia","dɪˈmenʃə","n.","痴呆"],
["s2","health","dental","ˈdentl","adj.","牙齿的"],
["s2","health","depression","dɪˈpreʃn","n.","抑郁"],
["s2","health","diabetes","ˌdaɪəˈbiːtiːz","n.","糖尿病"],
["s2","health","diagnose","ˈdaɪəɡnəʊz","v.","诊断"],
["s2","health","diet","ˈdaɪət","n.","饮食"],
["s2","health","disability","ˌdɪsəˈbɪləti","n.","残疾"],
["s2","health","disease","dɪˈziːz","n.","疾病"],
["s2","health","disorder","dɪsˈɔːdə(r)","n.","紊乱"],
["s2","health","doctor","ˈdɒktə(r)","n.","医生"],
["s2","health","dose","dəʊs","n.","剂量"],
["s2","health","drug","drʌɡ","n.","药"],
["s2","health","emergency","iˈmɜːdʒənsi","n.","紧急"],
["s2","health","epidemic","ˌepɪˈdemɪk","n./adj.","流行病","Public health officials warned of a possible flu <b>epidemic</b>.","C10 L S4"],
["s2","health","exercise","ˈeksəsaɪz","n./v.","锻炼"],
["s2","health","faint","feɪnt","v./adj.","昏厥；微弱的"],
["s2","health","fatal","ˈfeɪtl","adj.","致命的"],
["s2","health","fatigue","fəˈtiːɡ","n.","疲劳"],
["s2","health","fertility","fəˈtɪləti","n.","生育力"],
["s2","health","fever","ˈfiːvə(r)","n.","发烧"],
["s2","health","fitness","ˈfɪtnəs","n.","健康"],
["s2","health","flu","fluː","n.","流感"],
["s2","health","fracture","ˈfræktʃə(r)","n.","骨折"],
["s2","health","gene","dʒiːn","n.","基因"],
["s2","health","genetic","dʒəˈnetɪk","adj.","遗传的"],
["s2","health","germ","dʒɜːm","n.","细菌"],
["s2","health","gym","dʒɪm","n.","健身房"],
["s2","health","heal","hiːl","v.","治愈"],
["s2","health","health","helθ","n.","健康"],
["s2","health","healthcare","ˈhelθkeə(r)","n.","医疗保健"],
["s2","health","heart","hɑːt","n.","心脏"],
["s2","health","heart attack","hɑːt əˈtæk","n.","心脏病"],
["s2","health","heredity","həˈredəti","n.","遗传"],
["s2","health","hospital","ˈhɒspɪtl","n.","医院"],
["s2","health","hygiene","ˈhaɪdʒiːn","n.","卫生"],
["s2","health","illness","ˈɪlnəs","n.","疾病"],
["s2","health","immune","ɪˈmjuːn","adj.","免疫的"],
["s2","health","infection","ɪnˈfekʃn","n.","感染"],
["s2","health","ingredient","ɪnˈɡriːdiənt","n.","成分"],
["s2","health","injection","ɪnˈdʒekʃn","n.","注射"],
["s2","health","injury","ˈɪndʒəri","n.","伤害"],
["s2","health","insomnia","ɪnˈsɒmniə","n.","失眠"],
["s2","health","insurance","ɪnˈʃʊərəns","n.","保险"],
["s2","health","intensive care","ɪnˈtensɪv keə(r)","n.","重症护理"],
["s2","health","junk food","dʒʌŋk fuːd","n.","垃圾食品"],
["s2","health","laboratory","ləˈbɒrətri","n.","实验室"],
["s2","health","life expectancy","laɪf ɪkˈspektənsi","n.","预期寿命"],
["s2","health","lifestyle","ˈlaɪfstaɪl","n.","生活方式"],
["s2","health","mainstream","ˈmeɪnstriːm","adj.","主流的"],
["s2","health","malnutrition","ˌmælnjuːˈtrɪʃn","n.","营养不良"],
["s2","health","medicate","ˈmedɪkeɪt","v.","用药治疗"],
["s2","health","medication","ˌmedɪˈkeɪʃn","n.","药物"],
["s2","health","medicine","ˈmedsn","n.","药；医学"],
["s2","health","medical","ˈmedɪkl","adj.","医学的"],
["s2","health","mental","ˈmentl","adj.","精神的"],
["s2","health","mortality","mɔːˈtæləti","n.","死亡率"],
["s2","health","nurse","nɜːs","n.","护士"],
["s2","health","nutrient","ˈnjuːtriənt","n.","营养"],
["s2","health","nutrition","njuˈtrɪʃn","n.","营养","Good <b>nutrition</b> in early childhood is crucial.","C11 L S4"],
["s2","health","obesity","əʊˈbiːsəti","n.","肥胖","Childhood <b>obesity</b> rates have tripled since the 1980s.","C13 W2"],
["s2","health","obstetric","əbˈstetrɪk","adj.","产科的"],
["s2","health","operation","ˌɒpəˈreɪʃn","n.","手术"],
["s2","health","outbreak","ˈaʊtbreɪk","n.","爆发"],
["s2","health","pain","peɪn","n.","疼痛"],
["s2","health","painkiller","ˈpeɪnkɪlə(r)","n.","止痛药"],
["s2","health","pandemic","pænˈdemɪk","n.","大流行病"],
["s2","health","patient","ˈpeɪʃnt","n.","病人"],
["s2","health","physical","ˈfɪzɪkl","adj.","身体的"],
["s2","health","physician","fɪˈzɪʃn","n.","内科医生"],
["s2","health","pill","pɪl","n.","药片"],
["s2","health","plaster","ˈplɑːstə(r)","n.","创可贴"],
["s2","health","poison","ˈpɔɪzn","n./v.","毒"],
["s2","health","posture","ˈpɒstʃə(r)","n.","姿势"],
["s2","health","prescription","prɪˈskrɪpʃn","n.","处方"],
["s2","health","prescribe","prɪˈskraɪb","v.","开处方"],
["s2","health","preventive","prɪˈventɪv","adj.","预防的"],
["s2","health","protein","ˈprəʊtiːn","n.","蛋白质"],
["s2","health","psychiatrist","saɪˈkaɪətrɪst","n.","精神病学家"],
["s2","health","psychology","saɪˈkɒlədʒi","n.","心理学"],
["s2","health","pulse","pʌls","n.","脉搏"],
["s2","health","quarantine","ˈkwɒrəntiːn","n.","隔离"],
["s2","health","recover","rɪˈkʌvə(r)","v.","康复"],
["s2","health","regimen","ˈredʒɪmən","n.","养生法"],
["s2","health","rehabilitation","ˌriːəˌbɪlɪˈteɪʃn","n.","康复"],
["s2","health","relapse","rɪˈlæps","n./v.","复发"],
["s2","health","sedentary","ˈsednt(ə)ri","adj.","久坐的","Office workers often lead a highly <b>sedentary</b> lifestyle.","C14 R"],
["s2","health","skin","skɪn","n.","皮肤"],
["s2","health","sleep","sliːp","n./v.","睡眠"],
["s2","health","stamina","ˈstæmɪnə","n.","耐力"],
["s2","health","sterile","ˈsteraɪl","adj.","无菌的"],
["s2","health","strain","streɪn","n./v.","拉伤；压力"],
["s2","health","stress","stres","n.","压力"],
["s2","health","stroke","strəʊk","n.","中风"],
["s2","health","subsidy","ˈsʌbsədi","n.","补贴"],
["s2","health","suffer","ˈsʌfə(r)","v.","遭受"],
["s2","health","supplement","ˈsʌplɪmənt","n.","补充剂"],
["s2","health","surgeon","ˈsɜːdʒən","n.","外科医生"],
["s2","health","surgery","ˈsɜːdʒəri","n.","手术"],
["s2","health","symptom","ˈsɪmptəm","n.","症状"],
["s2","health","syndrome","ˈsɪndrəʊm","n.","综合症"],
["s2","health","therapy","ˈθerəpi","n.","治疗"],
["s2","health","tissue","ˈtɪʃuː","n.","组织"],
["s2","health","tonic","ˈtɒnɪk","n.","补品"],
["s2","health","toxic","ˈtɒksɪk","adj.","有毒的"],
["s2","health","tumour","ˈtjuːmə(r)","n.","肿瘤"],
["s2","health","ulcer","ˈʌlsə(r)","n.","溃疡"],
["s2","health","vaccinate","ˈvæksɪneɪt","v.","接种疫苗"],
["s2","health","vaccine","ˈvæksiːn","n.","疫苗","A new <b>vaccine</b> against malaria has shown 75% efficacy in trials.","C17 R"],
["s2","health","vein","veɪn","n.","静脉"],
["s2","health","ventilation","ˌventɪˈleɪʃn","n.","通风"],
["s2","health","virus","ˈvaɪrəs","n.","病毒"],
["s2","health","vitamin","ˈvɪtəmɪn","n.","维生素"],
["s2","health","wellbeing","ˌwelˈbiːɪŋ","n.","幸福；健康"],
["s2","health","wound","wuːnd","n.","伤口"],

]);
